// Formation presets with normalized coordinates (0-100 range)
export const PRESETS = {
  '4-3-3': [
    { id: 'gk', label: 'GK', xNorm: 50, yNorm: 90 },
    { id: 'lb', label: 'LB', xNorm: 20, yNorm: 70 },
    { id: 'cb1', label: 'CB', xNorm: 40, yNorm: 70 },
    { id: 'cb2', label: 'CB', xNorm: 60, yNorm: 70 },
    { id: 'rb', label: 'RB', xNorm: 80, yNorm: 70 },
    { id: 'cdm', label: 'CDM', xNorm: 50, yNorm: 50 },
    { id: 'cm1', label: 'CM', xNorm: 35, yNorm: 40 },
    { id: 'cm2', label: 'CM', xNorm: 65, yNorm: 40 },
    { id: 'lw', label: 'LW', xNorm: 20, yNorm: 25 },
    { id: 'st', label: 'ST', xNorm: 50, yNorm: 20 },
    { id: 'rw', label: 'RW', xNorm: 80, yNorm: 25 },
  ],
  '4-4-2': [
    { id: 'gk', label: 'GK', xNorm: 50, yNorm: 90 },
    { id: 'lb', label: 'LB', xNorm: 20, yNorm: 70 },
    { id: 'cb1', label: 'CB', xNorm: 40, yNorm: 70 },
    { id: 'cb2', label: 'CB', xNorm: 60, yNorm: 70 },
    { id: 'rb', label: 'RB', xNorm: 80, yNorm: 70 },
    { id: 'lm', label: 'LM', xNorm: 20, yNorm: 45 },
    { id: 'cm1', label: 'CM', xNorm: 40, yNorm: 45 },
    { id: 'cm2', label: 'CM', xNorm: 60, yNorm: 45 },
    { id: 'rm', label: 'RM', xNorm: 80, yNorm: 45 },
    { id: 'st1', label: 'ST', xNorm: 40, yNorm: 20 },
    { id: 'st2', label: 'ST', xNorm: 60, yNorm: 20 },
  ],
  '3-5-2': [
    { id: 'gk', label: 'GK', xNorm: 50, yNorm: 90 },
    { id: 'cb1', label: 'CB', xNorm: 30, yNorm: 70 },
    { id: 'cb2', label: 'CB', xNorm: 50, yNorm: 70 },
    { id: 'cb3', label: 'CB', xNorm: 70, yNorm: 70 },
    { id: 'lwb', label: 'LWB', xNorm: 15, yNorm: 55 },
    { id: 'cm1', label: 'CM', xNorm: 35, yNorm: 50 },
    { id: 'cdm', label: 'CDM', xNorm: 50, yNorm: 45 },
    { id: 'cm2', label: 'CM', xNorm: 65, yNorm: 50 },
    { id: 'rwb', label: 'RWB', xNorm: 85, yNorm: 55 },
    { id: 'st1', label: 'ST', xNorm: 40, yNorm: 20 },
    { id: 'st2', label: 'ST', xNorm: 60, yNorm: 20 },
  ],
  
  '3-4-3': [
    { id: 'gk', label: 'GK', xNorm: 50, yNorm: 90 },
    { id: 'cb1', label: 'CB', xNorm: 30, yNorm: 70 },
    { id: 'cb2', label: 'CB', xNorm: 50, yNorm: 70 },
    { id: 'cb3', label: 'CB', xNorm: 70, yNorm: 70 },
    { id: 'lm', label: 'LM', xNorm: 20, yNorm: 50 },
    { id: 'cm1', label: 'CM', xNorm: 40, yNorm: 50 },
    { id: 'cm2', label: 'CM', xNorm: 60, yNorm: 50 },
    { id: 'rm', label: 'RM', xNorm: 80, yNorm: 50 },
    { id: 'lw', label: 'LW', xNorm: 25, yNorm: 25 },
    { id: 'st', label: 'ST', xNorm: 50, yNorm: 20 },
    { id: 'rw', label: 'RW', xNorm: 75, yNorm: 25 },
  ],
  
  '4-2-3-1': [
    { id: 'gk', label: 'GK', xNorm: 50, yNorm: 90 },
    { id: 'lb', label: 'LB', xNorm: 20, yNorm: 70 },
    { id: 'cb1', label: 'CB', xNorm: 40, yNorm: 70 },
    { id: 'cb2', label: 'CB', xNorm: 60, yNorm: 70 },
    { id: 'rb', label: 'RB', xNorm: 80, yNorm: 70 },
    { id: 'cdm1', label: 'CDM', xNorm: 40, yNorm: 55 },
    { id: 'cdm2', label: 'CDM', xNorm: 60, yNorm: 55 },
    { id: 'cam1', label: 'CAM', xNorm: 30, yNorm: 35 },
    { id: 'cam2', label: 'CAM', xNorm: 50, yNorm: 35 },
    { id: 'cam3', label: 'CAM', xNorm: 70, yNorm: 35 },
    { id: 'st', label: 'ST', xNorm: 50, yNorm: 20 },
  ],
  
  '4-1-4-1': [
    { id: 'gk', label: 'GK', xNorm: 50, yNorm: 90 },
    { id: 'lb', label: 'LB', xNorm: 20, yNorm: 70 },
    { id: 'cb1', label: 'CB', xNorm: 40, yNorm: 70 },
    { id: 'cb2', label: 'CB', xNorm: 60, yNorm: 70 },
    { id: 'rb', label: 'RB', xNorm: 80, yNorm: 70 },
    { id: 'cdm', label: 'CDM', xNorm: 50, yNorm: 55 },
    { id: 'lm', label: 'LM', xNorm: 20, yNorm: 40 },
    { id: 'cm1', label: 'CM', xNorm: 40, yNorm: 40 },
    { id: 'cm2', label: 'CM', xNorm: 60, yNorm: 40 },
    { id: 'rm', label: 'RM', xNorm: 80, yNorm: 40 },
    { id: 'st', label: 'ST', xNorm: 50, yNorm: 20 },
  ],
  
  '5-2-2-1': [
    { id: 'gk', label: 'GK', xNorm: 50, yNorm: 90 },
    { id: 'lwb', label: 'LWB', xNorm: 10, yNorm: 70 },
    { id: 'cb1', label: 'CB', xNorm: 30, yNorm: 70 },
    { id: 'cb2', label: 'CB', xNorm: 50, yNorm: 70 },
    { id: 'cb3', label: 'CB', xNorm: 70, yNorm: 70 },
    { id: 'rwb', label: 'RWB', xNorm: 90, yNorm: 70 },
    { id: 'cm1', label: 'CM', xNorm: 40, yNorm: 50 },
    { id: 'cm2', label: 'CM', xNorm: 60, yNorm: 50 },
    { id: 'cam1', label: 'CAM', xNorm: 35, yNorm: 35 },
    { id: 'cam2', label: 'CAM', xNorm: 65, yNorm: 35 },
    { id: 'st', label: 'ST', xNorm: 50, yNorm: 20 },
  ],
  
  '4-1-2-1-2': [
    { id: 'gk', label: 'GK', xNorm: 50, yNorm: 90 },
    { id: 'lb', label: 'LB', xNorm: 20, yNorm: 70 },
    { id: 'cb1', label: 'CB', xNorm: 40, yNorm: 70 },
    { id: 'cb2', label: 'CB', xNorm: 60, yNorm: 70 },
    { id: 'rb', label: 'RB', xNorm: 80, yNorm: 70 },
    { id: 'cdm', label: 'CDM', xNorm: 50, yNorm: 55 },
    { id: 'lcm', label: 'CM', xNorm: 35, yNorm: 45 },
    { id: 'rcm', label: 'CM', xNorm: 65, yNorm: 45 },
    { id: 'cam', label: 'CAM', xNorm: 50, yNorm: 35 },
    { id: 'lst', label: 'ST', xNorm: 40, yNorm: 20 },
    { id: 'rst', label: 'ST', xNorm: 60, yNorm: 20 },
  ],
  
  '4-5-1': [
    { id: 'gk', label: 'GK', xNorm: 50, yNorm: 90 },
    { id: 'lb', label: 'LB', xNorm: 20, yNorm: 70 },
    { id: 'cb1', label: 'CB', xNorm: 40, yNorm: 70 },
    { id: 'cb2', label: 'CB', xNorm: 60, yNorm: 70 },
    { id: 'rb', label: 'RB', xNorm: 80, yNorm: 70 },
    { id: 'lm', label: 'LM', xNorm: 15, yNorm: 45 },
    { id: 'lcm', label: 'CM', xNorm: 35, yNorm: 45 },
    { id: 'cm', label: 'CM', xNorm: 50, yNorm: 45 },
    { id: 'rcm', label: 'CM', xNorm: 65, yNorm: 45 },
    { id: 'rm', label: 'RM', xNorm: 85, yNorm: 45 },
    { id: 'st', label: 'ST', xNorm: 50, yNorm: 20 },
  ],
  
  '4-2-2-2': [
    { id: 'gk', label: 'GK', xNorm: 50, yNorm: 90 },
    { id: 'lb', label: 'LB', xNorm: 20, yNorm: 70 },
    { id: 'cb1', label: 'CB', xNorm: 40, yNorm: 70 },
    { id: 'cb2', label: 'CB', xNorm: 60, yNorm: 70 },
    { id: 'rb', label: 'RB', xNorm: 80, yNorm: 70 },
    { id: 'cdm1', label: 'CDM', xNorm: 40, yNorm: 55 },
    { id: 'cdm2', label: 'CDM', xNorm: 60, yNorm: 55 },
    { id: 'lcam', label: 'CAM', xNorm: 35, yNorm: 40 },
    { id: 'rcam', label: 'CAM', xNorm: 65, yNorm: 40 },
    { id: 'lst', label: 'ST', xNorm: 40, yNorm: 20 },
    { id: 'rst', label: 'ST', xNorm: 60, yNorm: 20 },
  ],
};

// Initial dummy subs with sequential naming
export const DEFAULT_SUBS = [
  { id: 'dummy-12', label: 'SUB', position: 'ST', jerseyNumber: '12', playerName: 'Player 12' },
  { id: 'dummy-13', label: 'SUB', position: 'CAM', jerseyNumber: '13', playerName: 'Player 13' },
  { id: 'dummy-14', label: 'SUB', position: 'LM', jerseyNumber: '14', playerName: 'Player 14' },
  { id: 'dummy-15', label: 'SUB', position: 'CDM', jerseyNumber: '15', playerName: 'Player 15' },
  { id: 'dummy-16', label: 'SUB', position: 'RB', jerseyNumber: '16', playerName: 'Player 16' },
  { id: 'dummy-17', label: 'SUB', position: 'CB', jerseyNumber: '17', playerName: 'Player 17' },
  { id: 'dummy-18', label: 'SUB', position: 'GK', jerseyNumber: '18', playerName: 'Player 18' },
  { id: 'dummy-19', label: 'SUB', position: 'UT', jerseyNumber: 'UT', playerName: 'Placeholder', isPlaceholder: true },
];
